name: mboilerplateflutter
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  bloc: ^8.1.4
  bloc_test: ^9.1.7
  crypto: ^3.0.6
  dartz: ^0.10.1
  dio: ^5.7.0
  equatable: ^2.0.5
  firebase_analytics: ^11.3.4
  firebase_core: ^3.7.0
  firebase_crashlytics: ^4.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.2.1
  flutter_native_splash: ^2.4.2
  formz: ^0.8.0
  get_it: ^8.0.2
  go_router: ^14.4.1
  hydrated_bloc: ^9.1.5
  intl: ^0.19.0
  path_provider: ^2.1.5
  pretty_dio_logger: ^1.4.0
  shimmer: ^3.0.0
  vector_graphics: ^1.1.14

dev_dependencies:
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  mocktail: ^1.0.4
  vector_graphics_compiler: ^1.1.12

flutter:
  uses-material-design: true
  assets:
    - path: assets/svg/
      transformers:
        - package: vector_graphics_compiler
    - assets/images/
    - lib/core/common/environment/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
